### ISSUE TITLE
Nrlsmf error message when nrlolsr makes the routing

### ISSUE THREAD

**Issue by giannhspap24** [USNavalResearchLaboratory/nrlsmf#8]
#err
Could not recv pipe()

#steps
1.install nrlolsr
2. set up nrlolsr as service
3. install nrlsmf
4. execute nrlsmf(simple configuration, nrlsmf resequence...)
5. Error

4a. Create multicast MGEN traffic
5b. execute nrlsmf
#platform
CORE/EMANE
#source
Inspired by this paper:
https://www.semanticscholar.org/paper/Scaling-NS-3-DCE-Experiments-on-Multi-Core-Servers-Wiggins-Veytser/c5a91753f3274db36cf82e79b29cf683b2145740

**Comment by weston-nrl** [comment]
NRLOLSR and NRLSMF can communicate with each other using a 'protopipe' to provide relay set information to NRLSMF.  The name of that pipe is controlled by the 'instance' commandline parameter of nrlsmf and the '-smfclient' commandline parameter of nrlolsrd -- those parameters must match on a given node in order to work correctly.  Additionally, in a CORE environment, they must be different for each node because they are implemented as a file descriptor in /tmp, which is common across all CORE nodes.  You can look at the default CORE services for NRLOLSR and NRLSMF to see how they handle that, if you're trying to customize something.

If this does not address your problem, please provide the full error message and commandlines for nrlolsrd and nrlsmf.

**Comment by 1328720068** [comment]
Hi author, sorry to interrupt, but I saw in the nrlsmf article on GitHub that you raised a question about setting up nrlolsr and implementing nrlsmf in core/emane. At present, I have no idea how to execute the nrlsmf service in the core node. I successfully built the nrlsmf but failed to find this command when executing the nrlsmf.
In your spare time, can you describe to me how you set up the nrlolsr service and execute nrlsmf on a node in core/emane

**Comment by weston-nrl** [comment]
As noted in your other thread, it's as simple as building them and having the executables in your PATH so that you can run them by name from anywhere on the system (that is, by running "nrlsmf" not "./nrlsmf" or "/path/to/my/nrlsmf").
